flaskr/models.py
from flaskr import db,login_manager
from flask_bcrypt import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime,timedelta
from uuid import uuid4

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(UserMixin,db.Model):

    __tablename__='users'

    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(64),index=True)
    email=db.Column(db.String(64),unique=True,index=True)
    password=db.Column(
        db.String(128),
        default=generate_password_hash('snsflaskapp')
    )
    picture_path=db.Column(db.Text)
    is_active=db.Column(db.Boolean, unique=False,default=False)
    create_at=db.Column(db.DateTime,default=datetime.now)
    update_at=db.Column(db.DateTime,default=datetime.now)

    def __init__(self,username,email):
        self.username=username
        self.email=email

    @classmethod
    def select_user_by_email(cls,email):
        return cls.query.filter_by(email=email).first()

    def validate_password(self,password):
        return check_password_hash(self.passowrd,password)

    def create_new_user(self):
        db.session.add(self)

    @classmethod
    def select_user_by_id(cls,id):
        return cls.query.get(id)

    def save_new_password(self,new_password):
        self.password=generate_password_hash(new_password)
        self.is_active=True

class PasswordResetToken(db.Model):
    __tablename__ = 'password_reset_tokens'

    id=db.Column(db.Integer,primary_key=True)
    token=db.Column(
        db.String(64),
        unique=True,
        index=True,
        server_default=str(uuid4)
    )
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)
    expire_id=db.Column(db.DateTime,default=datetime.now)
    create_at=db.Column(db.DateTime,default=datetime.now)
    update_at=db.Column(db.DateTime,default=datetime.now)
    
    def __init__(self,token,user_id,expire_at):
        self.token=token
        self.user_id=user_id
        self.expire_at=expire_at

    @classmethod
    def publish_token(cls,user):
        token=str(uuid4())
        new_token=cls(
            token,
            user.id,
            datetime.now() +timedelta(days=1)
        )
        db.session.add(new_token)
        return token

    @classmethod
    def get_user_id_by_token(cls,token):
        now=datetime.now()
        record = cls.query.filter_by(token=str(token)).filter(cls.expire_at>now).first()
        return record.user_id

    @classmethod
    def delete_token(cls,token):
        cls.query.filter_by(token=str(token)).delete()

flaskr/forms.py
from wtforms.form import Form
from wtforms.fields import (
    StringField,FileField,PasswordField,SubmitField,HiddenField
)
from wtforms.validators import DataRequired,Email,EqualTo
from wtforms import ValidationError
from flaskr.models import User

class LoginForm(Form):
    email = StringField('メール：',validators=[DataRequired(),Email()])
    password=PasswordField(
        'パスワード：',
        validators=[DataRequired(),EqualTo('confirm_password',message='パスワードが一致しません')]
        )
    confirm_password=PasswordField('パスワード再入力：',validators=[DataRequired()])
    submit=SubmitField('ログイン')

class RegisterForm(Form):
    email=StringField('メール：',validators=[DataRequired(),Email('メールアドレスが誤っています')])
    username=StringField('名前：',validators=[DataRequired()])
    submit=SubmitField('登録')

    def validate_email(self,field):
        if User.select_user_by_email(field.data):
            raise ValidationError('メールアドレスは既に存在します')

class ResetPasswordForm(Form):
    password=PasswordField(
        'パスワード：',
        validators=[DataRequired(),EqualTo('confirm_password',message='パスワード')]
    )
    confirm_password=PasswordField(
        'パスワード確認：',validators=[DataRequired()]   
    )
    submit = SubmitField('パスワードを更新する')
    def validate_password(self,field):
        if len(field.data)<8:
            raise ValidationError('パスワードは8文字以上です')

flaskr/__init__.py
import os 
from flask import Flask
from flask_login import login_manager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login_manager= LoginManager()
login_manager.login_view='app.view'
login_manager.login_message='ログインしてください'

basedir = os.path.abspath(os.path.dirname(__name__))
db=SQLAlchemy()
migrate=Migrate()

def create_app():
    app=Flask(__name__)
    app.config['SECRET_KEY'] = 'mysite'
    app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///'+os.path.join(basedir,'data.sqlite')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False
    from flaskr.views import bp
    app.register_blueprint(bp)
    db.init_app(app)
    migrate.init_app(app,db)
    login_manager.init_app(app)
    return app

flaskr/views.py
from flask import (
    Blueprint,abort,request,render_template,
    redirect,url_for,flash
)
from flask_login import login_user,login_required,login_user
from flaskr.models import (
    User,PasswordResetToken
)
from flaskr import db

from flaskr.forms import (
    LoginForm,RegisterForm,ResetPasswordForm
)

bp=Blueprint('app',__name__,url_prefix='')

@bp.route('/')
def home():
    return render_template('home.html')

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('app.home'))

@bp.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_email(form.email.data)
        if user and user.is_active and user.validate_password(form.password.data):
            login_user(user,remember=True)
            next=request.args.get('next')
            if not next:
                next=url_for('app.home')
            return redirect(next)
        elif not user:
            flash('存在しないユーザです')
        elif not user.is_active:
            flash('無効なユーザです。パスワードを再設定してください')
        elif not user.validate_password(form.password.data):
            flash('メールアドレスとパスワードの組み合わせが誤っています。')
    return render_template('login.html',form=form)

@bp.route('/register',methods=['GET','POST'])
def register():
    form =RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user=User(
            username=form.username.data,
            email=form.email.data
        )
        with db.session.begin(subtransactions=True):
            user.create_new_user()
        db.session.commit()
        token=''
        with db.session.begin(subtransactions=True):
            token=PasswordResetToken.publish_token(user)
            db.session.commit()
            #メールに飛ばす方が良いがメールサーバが必要なので今回は画面表示にする。
            print(
                f'パスワード設定用URL： http://127.0.0.1:5000/reset_password/{token}'
            )
            flash('パスワード設定用のURLをお送りしました。ご確認ください')
        return redirect(url_for('app.login'))
    return render_template('register.html',form=form)

@bp.route('/reset_password/<uuid:token>',methods=['GET','POST'])
def reset_password(token):
    form = ResetPasswordForm(request.form)
    reset_user_id=PasswordResetToken.get_user_id_by_token(token)
    if not reset_user_id:
        abort(500)
    if request.method=='POST' and form.validate():
        password=form.password.data
        user=User.select_user_by_id(reset_user_id)
        with db.session.begin(substransactions=True):
            user.save_new_password(password)
            PasswordResetToken.delete_token(token)
        db.session.commit()
        flash('パスワードを更新しました。')
        return redirect(url_for('app.login'))
    return render_template('reset_password.html',form=form)

flaskr/templates/_formhelpers.html
{%macro render_field(field)%}
<dt>
    {{field.label}}
<dd>
    {{field(**kwargs)|safe}}
    {%if field.errors %}
    <ul class="errors">
        {%for error in field.errors%}
        <li>{{error}}</li>
        {%endfor%}
    </ul>
    {%endif%}
</dd>
</dt>
{%endmacro%}

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{%block title%}FlASK SNS{%endblock%}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{url_for('app.home')}}">
            ホーム
        </a>
        {%if current_user.is_authenticated%}
        <a class="navbar-brand" href="{{url_for('app.logout')}}">
            ログアウト
        </a>
        {% else %}
        <a class="navbar-brand" href="{{url_for('app.login')}}">
            ログイン
        </a>
        <a class="navbar-brand" href="{{url_for('app.register')}}">
            登録
        </a>
        {%endif%}
    </nav>
    <div class = "container">
        {%block content%}
        {%endblock%}
    </div>
</body>
</html>

flaskr/templates/home.html
{%extends "base.html"%}
{%block title%}
ホーム - {{super()}}
{%endblock%}
{%block content%}
<div class = "row">
    {%if current_user.is_authenticated%}
    <div class="col-lg-4 offset-lg-2">
        {%if current_user.picture_path%}
            <img src="{{url_for('static',filename=current_user.picture_path)}}" >
        {%endif%}
    </div>
    <div class ="col-lg-4 offset-lg-2">
        <p>ユーザ名：{{current_user.username}}</p>
        <p>メールアドレス：{{current_user.email}}</p>
    </div>
    {%else%}
        <p>ログイン or 登録をしてください</p>
    {%endif%}
</div>
{%endblock%}

flaskr/templates/login.html
{%from "_formhelpers.html" import render_field%}
{%extends "base.html"%}
{%block title%}
ログイン - {{super()}}
{%endblock%}
{%block content%}
{%for message in get_flashed_messages()%}
{{message}}
{%endfor%}
<div class = "row">
    <form method="POST">
        {{form.csrf_token}}
        {{render_field(form.email)}}
        {{render_field(form.password)}}
        {{render_field(form.confirm_password )}}
        {{form.submit()}}
    </form>
</div>
{%endblock%}

flaskr/templates/register.html
{%from "_formhelpers.html" import render_field%}
{%extends "base.html"%}
{%block title%}
ユーザ登録 - {{super()}}
{%endblock%}
{%block content%}
<h1>ユーザ情報登録画面</h1>
<div class = "row">
    <form method="POST">
        {{form.csrf_token}}
        {{render_field(form.username)}}
        {{render_field(form.email)}}
        {{form.submit()}}
    </form>
</div>
{%endblock%}

flaskr/templates/reset_password.html
{%from "_formhelpers.html" import render_field%}
{%extends "base.html"%}
{%block title%}
パスワード登録 - {{super()}}
{%endblock%}
{%block content%}
<h1>パスワード登録画面</h1>
<div class = "row">
    <form method="POST">
        {{form.csrf_token}}
        {{render_field(form.password)}}
        {{render_field(form.confirm_password)}}
        {{form.submit()}}
    </form>
</div>
{%endblock%}